
packages:
  - packages/api/handlers/typescript
  - packages/api/generated/infrastructure/typescript
  - packages/api/generated/libraries/typescript-react-query-hooks
  - packages/api/generated/runtime/typescript
  - packages/website
  - packages/infra
