
[tool.poetry]
name = "amzn-smart-product-onboarding-metaclasses"
version = "0.1.0"
description = ""
authors = [ "AWS Latam PACE <aws-latam-pace@amazon.com>" ]
readme = "README.md"

  [tool.poetry.dependencies]
  cachetools = "^5.5.1"
  faiss-cpu = "^1.10.0"
  inflect = "^7.4.0"
  jinja2 = "^3.1.4"
  nltk = "^3.9.1"
  numpy = "^2.2.2"
  python = "^3.12"

    [tool.poetry.dependencies.amzn_smart_product_onboarding_api_python_runtime]
    path = "../api"
    develop = true

    [tool.poetry.dependencies.amzn_smart_product_onboarding_core_utils]
    path = "../core-utils"
    develop = true

[tool.poetry.group.dev.dependencies]
pytest = "7.4.3"

  [tool.poetry.group.dev.dependencies.boto3-stubs-lite]
  version = "^1.35.37"
  extras = [ "bedrock-runtime", "s3", "dynamodb" ]

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"
